// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nQda7rWVzXgi8R-A5Qeli4ywJOzm2Jg',
    appId: '1:6089230341:android:bf0beab6d3deb27b78346c',
    messagingSenderId: '6089230341',
    projectId: 'bluecrown-b1a49',
    databaseURL: 'https://bluecrown-b1a49-default-rtdb.firebaseio.com',
    storageBucket: 'bluecrown-b1a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZo91uBy87SAKI4Gw4qnus4yUxfgypSR4',
    appId: '1:6089230341:ios:0597ba91ec36a70f78346c',
    messagingSenderId: '6089230341',
    projectId: 'bluecrown-b1a49',
    databaseURL: 'https://bluecrown-b1a49-default-rtdb.firebaseio.com',
    storageBucket: 'bluecrown-b1a49.appspot.com',
    iosBundleId: 'com.bluecrowntemplate.blueCrownTemplate',
  );
}
