part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN_TYPE = _Paths.LOGIN_TYPE;
  static const LOGIN = _Paths.LOGIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const PASSWORD_RESET = _Paths.PASSWORD_RESET;
  static const CREATE_NEW_PASSWORD = _Paths.CREATE_NEW_PASSWORD;
  static const HOME = _Paths.HOME;
  static const NAVBAR = _Paths.NAVBAR;
  static const WARDROBE = _Paths.WARDROBE;
  static const SCANNER = _Paths.SCANNER;
  static const EVENT_DETAIL = _Paths.EVENT_DETAIL;
  static const LIST_REQUEST = _Paths.LIST_REQUEST;
  static const TABLE_REQUEST = _Paths.TABLE_REQUEST;
  static const USE_POINTS = _Paths.USE_POINTS;
  static const HISTORY = _Paths.HISTORY;
  static const WARDROBE_AVAILABILITY = _Paths.WARDROBE_AVAILABILITY;
  static const WARDROBE_SCANNER = _Paths.WARDROBE_SCANNER;
  static const BLUECROWN_POINT = _Paths.BLUECROWN_POINT;
  static const CLUB_EVENTS = _Paths.CLUB_EVENTS;
  static const CLUB_INFO = _Paths.CLUB_INFO;
  static const MY_PROFILE = _Paths.MY_PROFILE;
  static const LOGOUT = _Paths.LOGOUT;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const NOTIFICATION_SETTING = _Paths.NOTIFICATION_SETTING;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const TERMS_CONDITION = _Paths.TERMS_CONDITION;
  static const EVENT_WALLET_HISTORY = _Paths.EVENT_WALLET_HISTORY;
  static const REQUEST_LIST_HISTORY = _Paths.REQUEST_LIST_HISTORY;
  static const PROVIDER_NAV_BAR = _Paths.PROVIDER_NAV_BAR;
  static const PROVIDER_EVENT_DETAIL = _Paths.PROVIDER_EVENT_DETAIL;
  static const PROVIDER_CONSUMER_REGISTER = _Paths.PROVIDER_CONSUMER_REGISTER;
  static const PROVIDER_PUBLISH_EVENT = _Paths.PROVIDER_PUBLISH_EVENT;
  static const PROVIDER_WARDROBE = _Paths.PROVIDER_WARDROBE;
  static const PROVIDER_CREATE_QR_CODE = _Paths.PROVIDER_CREATE_QR_CODE;
  static const PROVIDER_DOWNLOAD_QR_CODE = _Paths.PROVIDER_DOWNLOAD_QR_CODE;
  static const PROVIDER_CONTACT_US = _Paths.PROVIDER_CONTACT_US;
  static const CONTACT_US = _Paths.CONTACT_US;
  static const PROVIDER_LIST_HISTORY = _Paths.PROVIDER_LIST_HISTORY;
  static const PROVIDER_CURRENT_LIST = _Paths.PROVIDER_CURRENT_LIST;
  static const PROVIDER_ADD_LIST = _Paths.PROVIDER_ADD_LIST;
  static const PROVIDER_ALL_EVENT = _Paths.PROVIDER_ALL_EVENT;
  static const PROVIDER_EDIT_EVENT = _Paths.PROVIDER_EDIT_EVENT;
  static const PROVIDER_PUSH_NOTIFICATION = _Paths.PROVIDER_PUSH_NOTIFICATION;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const OTP = _Paths.OTP;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const HOW_GET_POINT = _Paths.HOW_GET_POINT;
  static const PROVIDER_CONSUMER_LIST = _Paths.PROVIDER_CONSUMER_LIST;
  static const PROVIDER_PURCHASED_USERS = _Paths.PROVIDER_PURCHASED_USERS;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const LOGIN_TYPE = '/login-type';
  static const LOGIN = '/login';
  static const SIGNUP = '/signup';
  static const PASSWORD_RESET = '/password-reset';
  static const CREATE_NEW_PASSWORD = '/create-new-password';
  static const HOME = '/home';
  static const NAVBAR = '/nav-bar';
  static const WARDROBE = '/wardrobe';
  static const SCANNER = '/scanner';
  static const EVENT_DETAIL = '/event-detail';
  static const LIST_REQUEST = '/list-request';
  static const TABLE_REQUEST = '/table-request';
  static const USE_POINTS = '/use-points';
  static const HISTORY = '/history';
  static const WARDROBE_AVAILABILITY = '/wardrobe-availability';
  static const WARDROBE_SCANNER = '/wardrobe-scanner';
  static const BLUECROWN_POINT = '/blueCrown-point';
  static const CLUB_EVENTS = '/club-events';
  static const CLUB_INFO = '/club-info';
  static const MY_PROFILE = '/my-profile';
  static const LOGOUT = '/logout';
  static const CHANGE_PASSWORD = '/change-password';
  static const NOTIFICATION_SETTING = '/notification-setting';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const TERMS_CONDITION = '/terms-condition';
  static const EVENT_WALLET_HISTORY = '/event-wallet-history';
  static const REQUEST_LIST_HISTORY = '/request-list-history';
  static const PROVIDER_NAV_BAR = '/provider-nav-bar';
  static const PROVIDER_EVENT_DETAIL = '/provider-event-detail';
  static const PROVIDER_CONSUMER_REGISTER = '/provider-consumer-register';
  static const PROVIDER_PUBLISH_EVENT = '/provider-publish-event';
  static const PROVIDER_WARDROBE = '/provider-wardrobe';
  static const PROVIDER_CREATE_QR_CODE = '/provider-create-qr-code';
  static const PROVIDER_DOWNLOAD_QR_CODE = '/provider-download-qr-code';
  static const PROVIDER_CONTACT_US = '/provider-contact-us';
  static const CONTACT_US = '/contact-us';
  static const PROVIDER_LIST_HISTORY = '/provider-list-history';
  static const PROVIDER_CURRENT_LIST = '/provider-current-list';
  static const PROVIDER_ADD_LIST = '/provider-add-list';
  static const PROVIDER_ALL_EVENT = '/provider-all-event';
  static const PROVIDER_EDIT_EVENT = '/provider-edit-event';
  static const PROVIDER_PUSH_NOTIFICATION = '/provider-push-notification';
  static const NOTIFICATIONS = '/notifications';
  static const OTP = '/otp';
  static const NEW_PASSWORD = '/new-password';
  static const HOW_GET_POINT = '/how-get-point';
  static const PROVIDER_CONSUMER_LIST = '/provider-consumer-list';
  static const PROVIDER_PURCHASED_USERS = '/provider-purchased-users';
}
